name: tailscale

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Tailscale Action
        uses: ./
        with:
          authkey: ${{ secrets.AUTH_KEY }}

      - name: Run Tailscale
          shell: bash
          env:
            TAILSCALE_AUTHKEY: ${{ secrets.AUTH_KEY }}
          run: |
            sudo tailscaled 2>~/tailscaled.log &
            sudo tailscale up --authkey ${TAILSCALE_AUTHKEY} --accept-routes --shields-up

      - name: check for hello.ipn.dev in netmap
        run:
          tailscale status | grep -q hello
